# Generated by Django 6.0.3 on 2026-04-02 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0002_initial'),
        ('factures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='avocat',
            field=models.ForeignKey(limit_choices_to={'role': 'avocat'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='dossiers.client'),
        ),
        migrations.AddField(
            model_name='facture',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='dossiers.dossier'),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='factures.facture'),
        ),
    ]
