# Generated by Django 6.0.3 on 2026-04-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_audience', models.DateTimeField()),
                ('tribunal', models.CharField(max_length=200)),
                ('statut', models.CharField(choices=[('programmee', 'Programmée'), ('tenue', 'Tenue'), ('reportee', 'Reportée'), ('annulee', 'Annulée')], default='programmee', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('resultat', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
