# Generated by Django 6.0.3 on 2026-03-25 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du dossier')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('statut', models.CharField(choices=[('En cours', 'En cours'), ('Clôturé', 'Clôturé')], default='En cours', max_length=100, verbose_name='Statut')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Client associé')),
            ],
        ),
    ]
