# Generated by Django 6.0.3 on 2026-04-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('cin', models.CharField(blank=True, max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('clos', 'Clos')], default='ouvert', max_length=20)),
                ('date_ouverture', models.DateField(auto_now_add=True)),
                ('date_cloture', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('heures_travaillees', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
