# Generated by Django 6.0.3 on 2026-03-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('termine', models.BooleanField(default=False)),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
