# Generated by Django 6.0.3 on 2026-04-20 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_user_avocat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avocat',
        ),
    ]
