# Generated by Copilot on 2026-04-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avocat',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assistantes',
                to='utilisateurs.user',
            ),
        ),
    ]
