# Generated by Django 6.0.3 on 2026-03-25 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du document')),
                ('fichier', models.FileField(upload_to='documents/', verbose_name='Fichier')),
                ('date_ajout', models.DateField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Client associé')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossiers.dossier', verbose_name='Dossier associé')),
            ],
        ),
    ]
