# Generated by Django 6.0.3 on 2026-03-28 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_client_remove_document_date_ajout_and_more'),
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='date_creation',
            new_name='date_upload',
        ),
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='employe',
        ),
        migrations.RemoveField(
            model_name='document',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='document',
            name='type_document',
        ),
        migrations.AlterField(
            model_name='document',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossiers.dossier'),
        ),
    ]
