# Generated by Django 6.0.3 on 2026-03-28 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_audience', models.DateTimeField()),
                ('lieu', models.CharField(max_length=200)),
                ('statut', models.CharField(choices=[('prevue', 'Prévue'), ('reportee', 'Reportée'), ('terminee', 'Terminée')], default='prevue', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossiers.dossier')),
            ],
        ),
    ]
