# Generated by Django 6.0.3 on 2026-03-28 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiences', '0001_initial'),
        ('avocats', '0001_initial'),
        ('clients', '0001_initial'),
        ('dossiers', '0002_dossier_avocat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audience',
            name='lieu',
        ),
        migrations.AddField(
            model_name='audience',
            name='avocat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='avocats.avocat', verbose_name='Avocat'),
        ),
        migrations.AlterField(
            model_name='audience',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='audience',
            name='date_audience',
            field=models.DateField(verbose_name="Date de l'audience"),
        ),
        migrations.AlterField(
            model_name='audience',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossiers.dossier', verbose_name='Dossier'),
        ),
        migrations.AlterField(
            model_name='audience',
            name='statut',
            field=models.CharField(choices=[('Prévue', 'Prévue'), ('Clôturée', 'Clôturée')], default='Prévue', max_length=100),
        ),
    ]
