# Generated by Django 6.0.3 on 2026-04-02 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audiences', '0001_initial'),
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='avocat',
            field=models.ForeignKey(limit_choices_to={'role': 'avocat'}, on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audience',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='dossiers.dossier'),
        ),
    ]
